import { PieceSize, ModularPiece, PropCategory } from '@/types';

// D&D-based prop sizes in inches
export const PROP_SIZES: Record<string, PieceSize> = {
  tiny: { width: 0.5, height: 0.5, label: 'Tiny (0.5")' },
  medium: { width: 1, height: 1, label: 'Small/Medium (1")' },
  large: { width: 2, height: 2, label: 'Large (2")' },
  huge: { width: 3, height: 3, label: 'Huge (3")' },
  gargantuan: { width: 6, height: 6, label: 'Gargantuan (6")' },
};

// Prop category metadata
export const PROP_CATEGORIES: { id: PropCategory; name: string; icon: string }[] = [
  { id: 'furniture', name: 'Furniture', icon: '🪑' },
  { id: 'npc', name: 'NPCs', icon: '👤' },
  { id: 'creature', name: 'Creatures', icon: '🐺' },
  { id: 'hero', name: 'Heroes', icon: '🦸' },
  { id: 'boss', name: 'Bosses', icon: '👹' },
  { id: 'item', name: 'Items', icon: '📦' },
  { id: 'custom', name: 'Custom', icon: '✨' },
];

// Default props library (all start with quantity 0 - user adds to inventory as needed)
export const DEFAULT_PROPS: ModularPiece[] = [
  // Furniture (mostly medium to large)
  {
    id: 'prop-chair',
    name: 'Chair',
    pieceType: 'prop',
    propEmoji: '🪑',
    propCategory: 'furniture',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['furniture', 'seating', 'tavern', 'indoor'],
  },
  {
    id: 'prop-table',
    name: 'Table',
    pieceType: 'prop',
    propEmoji: '🍽️',
    propCategory: 'furniture',
    terrainTypeId: 'props',
    size: PROP_SIZES.large,
    isDiagonal: false,
    quantity: 0,
    tags: ['furniture', 'tavern', 'indoor', 'dining'],
  },
  {
    id: 'prop-bed',
    name: 'Bed',
    pieceType: 'prop',
    propEmoji: '🛏️',
    propCategory: 'furniture',
    terrainTypeId: 'props',
    size: PROP_SIZES.large,
    isDiagonal: false,
    quantity: 0,
    tags: ['furniture', 'bedroom', 'indoor', 'rest'],
  },
  {
    id: 'prop-throne',
    name: 'Throne',
    pieceType: 'prop',
    propEmoji: '🪑',
    propCategory: 'furniture',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['furniture', 'seating', 'royal', 'castle', 'indoor'],
  },
  {
    id: 'prop-barrel',
    name: 'Barrel',
    pieceType: 'prop',
    propEmoji: '🛢️',
    propCategory: 'furniture',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['furniture', 'storage', 'tavern', 'cellar'],
  },
  {
    id: 'prop-bookshelf',
    name: 'Bookshelf',
    pieceType: 'prop',
    propEmoji: '📚',
    propCategory: 'furniture',
    terrainTypeId: 'props',
    size: PROP_SIZES.large,
    isDiagonal: false,
    quantity: 0,
    tags: ['furniture', 'library', 'indoor', 'wizard', 'storage'],
  },

  // NPCs (mostly medium = humanoid)
  {
    id: 'prop-npc',
    name: 'NPC',
    pieceType: 'prop',
    propEmoji: '👤',
    propCategory: 'npc',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['npc', 'humanoid', 'person', 'civilian'],
  },
  {
    id: 'prop-guard',
    name: 'Guard',
    pieceType: 'prop',
    propEmoji: '💂',
    propCategory: 'npc',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['npc', 'humanoid', 'soldier', 'military', 'armor'],
  },
  {
    id: 'prop-merchant',
    name: 'Merchant',
    pieceType: 'prop',
    propEmoji: '🧑‍💼',
    propCategory: 'npc',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['npc', 'humanoid', 'shop', 'trade', 'market'],
  },
  {
    id: 'prop-wizard',
    name: 'Wizard',
    pieceType: 'prop',
    propEmoji: '🧙',
    propCategory: 'npc',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['npc', 'humanoid', 'magic', 'mage', 'spellcaster'],
  },
  {
    id: 'prop-villager',
    name: 'Villager',
    pieceType: 'prop',
    propEmoji: '🧑‍🌾',
    propCategory: 'npc',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['npc', 'humanoid', 'farmer', 'civilian', 'village'],
  },

  // Creatures
  {
    id: 'prop-horse',
    name: 'Horse',
    pieceType: 'prop',
    propEmoji: '🐴',
    propCategory: 'creature',
    terrainTypeId: 'props',
    size: PROP_SIZES.large,
    isDiagonal: false,
    quantity: 0,
    tags: ['creature', 'animal', 'mount', 'beast', 'outdoor'],
  },
  {
    id: 'prop-wolf',
    name: 'Wolf',
    pieceType: 'prop',
    propEmoji: '🐺',
    propCategory: 'creature',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['creature', 'animal', 'beast', 'enemy', 'forest'],
  },
  {
    id: 'prop-bear',
    name: 'Bear',
    pieceType: 'prop',
    propEmoji: '🐻',
    propCategory: 'creature',
    terrainTypeId: 'props',
    size: PROP_SIZES.large,
    isDiagonal: false,
    quantity: 0,
    tags: ['creature', 'animal', 'beast', 'enemy', 'forest'],
  },
  {
    id: 'prop-spider',
    name: 'Giant Spider',
    pieceType: 'prop',
    propEmoji: '🕷️',
    propCategory: 'creature',
    terrainTypeId: 'props',
    size: PROP_SIZES.large,
    isDiagonal: false,
    quantity: 0,
    tags: ['creature', 'monster', 'enemy', 'dungeon', 'cave'],
  },
  {
    id: 'prop-skeleton',
    name: 'Skeleton',
    pieceType: 'prop',
    propEmoji: '💀',
    propCategory: 'creature',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['creature', 'undead', 'enemy', 'dungeon', 'monster'],
  },
  {
    id: 'prop-zombie',
    name: 'Zombie',
    pieceType: 'prop',
    propEmoji: '🧟',
    propCategory: 'creature',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['creature', 'undead', 'enemy', 'dungeon', 'monster'],
  },

  // Heroes
  {
    id: 'prop-hero',
    name: 'Hero',
    pieceType: 'prop',
    propEmoji: '🦸',
    propCategory: 'hero',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['hero', 'player', 'humanoid', 'adventurer'],
  },
  {
    id: 'prop-warrior',
    name: 'Warrior',
    pieceType: 'prop',
    propEmoji: '⚔️',
    propCategory: 'hero',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['hero', 'player', 'fighter', 'melee', 'armor'],
  },
  {
    id: 'prop-mage',
    name: 'Mage',
    pieceType: 'prop',
    propEmoji: '🔮',
    propCategory: 'hero',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['hero', 'player', 'magic', 'spellcaster', 'wizard'],
  },
  {
    id: 'prop-rogue',
    name: 'Rogue',
    pieceType: 'prop',
    propEmoji: '🗡️',
    propCategory: 'hero',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['hero', 'player', 'stealth', 'thief', 'assassin'],
  },
  {
    id: 'prop-cleric',
    name: 'Cleric',
    pieceType: 'prop',
    propEmoji: '✝️',
    propCategory: 'hero',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['hero', 'player', 'healer', 'divine', 'priest'],
  },

  // Bosses (larger sizes)
  {
    id: 'prop-boss',
    name: 'Boss (Large)',
    pieceType: 'prop',
    propEmoji: '👹',
    propCategory: 'boss',
    terrainTypeId: 'props',
    size: PROP_SIZES.large,
    isDiagonal: false,
    quantity: 0,
    tags: ['boss', 'enemy', 'monster', 'encounter'],
  },
  {
    id: 'prop-ogre',
    name: 'Ogre',
    pieceType: 'prop',
    propEmoji: '👺',
    propCategory: 'boss',
    terrainTypeId: 'props',
    size: PROP_SIZES.large,
    isDiagonal: false,
    quantity: 0,
    tags: ['boss', 'enemy', 'monster', 'giant', 'cave'],
  },
  {
    id: 'prop-giant',
    name: 'Giant',
    pieceType: 'prop',
    propEmoji: '🗿',
    propCategory: 'boss',
    terrainTypeId: 'props',
    size: PROP_SIZES.huge,
    isDiagonal: false,
    quantity: 0,
    tags: ['boss', 'enemy', 'monster', 'giant', 'huge'],
  },
  {
    id: 'prop-dragon',
    name: 'Dragon',
    pieceType: 'prop',
    propEmoji: '🐉',
    propCategory: 'boss',
    terrainTypeId: 'props',
    size: PROP_SIZES.gargantuan,
    isDiagonal: false,
    quantity: 0,
    tags: ['boss', 'enemy', 'monster', 'dragon', 'flying', 'legendary'],
  },
  {
    id: 'prop-demon',
    name: 'Demon',
    pieceType: 'prop',
    propEmoji: '😈',
    propCategory: 'boss',
    terrainTypeId: 'props',
    size: PROP_SIZES.huge,
    isDiagonal: false,
    quantity: 0,
    tags: ['boss', 'enemy', 'monster', 'fiend', 'evil', 'hell'],
  },

  // Items
  {
    id: 'prop-chest',
    name: 'Chest',
    pieceType: 'prop',
    propEmoji: '📦',
    propCategory: 'item',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['item', 'loot', 'treasure', 'storage', 'dungeon'],
  },
  {
    id: 'prop-potion',
    name: 'Potion',
    pieceType: 'prop',
    propEmoji: '🧪',
    propCategory: 'item',
    terrainTypeId: 'props',
    size: PROP_SIZES.tiny,
    isDiagonal: false,
    quantity: 0,
    tags: ['item', 'loot', 'consumable', 'healing', 'magic'],
  },
  {
    id: 'prop-scroll',
    name: 'Scroll',
    pieceType: 'prop',
    propEmoji: '📜',
    propCategory: 'item',
    terrainTypeId: 'props',
    size: PROP_SIZES.tiny,
    isDiagonal: false,
    quantity: 0,
    tags: ['item', 'loot', 'magic', 'spell', 'readable'],
  },
  {
    id: 'prop-key',
    name: 'Key',
    pieceType: 'prop',
    propEmoji: '🗝️',
    propCategory: 'item',
    terrainTypeId: 'props',
    size: PROP_SIZES.tiny,
    isDiagonal: false,
    quantity: 0,
    tags: ['item', 'loot', 'quest', 'unlock', 'dungeon'],
  },
  {
    id: 'prop-gem',
    name: 'Gem',
    pieceType: 'prop',
    propEmoji: '💎',
    propCategory: 'item',
    terrainTypeId: 'props',
    size: PROP_SIZES.tiny,
    isDiagonal: false,
    quantity: 0,
    tags: ['item', 'loot', 'treasure', 'valuable', 'jewel'],
  },
  {
    id: 'prop-campfire',
    name: 'Campfire',
    pieceType: 'prop',
    propEmoji: '🔥',
    propCategory: 'item',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['item', 'environment', 'light', 'outdoor', 'rest'],
  },
  {
    id: 'prop-tree',
    name: 'Tree',
    pieceType: 'prop',
    propEmoji: '🌳',
    propCategory: 'item',
    terrainTypeId: 'props',
    size: PROP_SIZES.large,
    isDiagonal: false,
    quantity: 0,
    tags: ['item', 'environment', 'nature', 'outdoor', 'forest'],
  },
  {
    id: 'prop-rock',
    name: 'Rock',
    pieceType: 'prop',
    propEmoji: '🪨',
    propCategory: 'item',
    terrainTypeId: 'props',
    size: PROP_SIZES.medium,
    isDiagonal: false,
    quantity: 0,
    tags: ['item', 'environment', 'nature', 'outdoor', 'obstacle'],
  },
];

// Common emojis for custom prop creation
export const COMMON_PROP_EMOJIS = [
  // People
  '👤', '👥', '🧑', '👨', '👩', '🧙', '🧝', '🧛', '🧜', '🧞', '🦸', '🦹', '💂', '🤴', '👸',
  // Creatures
  '🐉', '🐺', '🐻', '🦁', '🦅', '🦇', '🕷️', '🦂', '🐍', '🐊', '🐙', '👹', '👺', '💀', '👻', '🧟', '🧌',
  // Items
  '⚔️', '🗡️', '🏹', '🛡️', '🔮', '📦', '🗝️', '💎', '🧪', '📜', '💰', '🪙', '🏆', '🎁',
  // Furniture
  '🪑', '🛏️', '🍽️', '📚', '🛢️', '🪤', '🚪', '🪟', '🪞', '🛋️',
  // Environment
  '🌳', '🌲', '🪨', '🔥', '💧', '🌊', '⭐', '☀️', '🌙', '⚡', '❄️', '🏔️', '🗻',
  // Buildings
  '🏠', '🏰', '⛪', '🏛️', '🏚️', '⛺', '🛖',
  // Misc
  '❓', '❗', '⚠️', '🚫', '✨', '💫', '🎭', '🎪',
];
